const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');

const targetUrl = process.argv[2] || 'https://yeswehack.com/auth/login';
const outputFile = 'C:\\BugBounty\\cookies.txt';

(async () => {
    console.log('[*] Launching Chrome browser...');
    console.log('[!] Please log in manually. Waiting for successful login...');

    // Launch a visible browser so the user can interact (solve captcha, 2FA, etc)
    const browser = await chromium.launch({ headless: false });
    const context = await browser.newContext();
    const page = await context.newPage();
    page.setDefaultNavigationTimeout(300000); // 5 minutes timeout for all navigations

    try {
        console.log(`[*] Navigating to ${targetUrl}...`);
        await page.goto(targetUrl);

        // Wait until the user lands on a page that isn't the login page
        await page.waitForFunction((url) => {
            return !window.location.href.includes('login') && !window.location.href.includes('challenge') && !window.location.href.includes('signin');
        }, targetUrl, { timeout: 300000 }); // 5 minutes timeout to allow time for typing and 2FA

        console.log('[+] Login detected!');
        console.log('[*] Extracting cookies...');

        // Get all cookies from the browser context
        const cookies = await context.cookies();
        
        let netscapeFormat = "# Netscape HTTP Cookie File\n";
        netscapeFormat += "# Generated by Antigravity auto-login.js\n\n";

        for (const cookie of cookies) {
            const domain = cookie.domain;
            // Netscape format rules for the 'include subdomains' flag
            const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
            const path = cookie.path;
            const secure = cookie.secure ? 'TRUE' : 'FALSE';
            const expires = Math.round(cookie.expires);
            const name = cookie.name;
            const value = cookie.value;

            netscapeFormat += `${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expires}\t${name}\t${value}\n`;
        }

        fs.writeFileSync(outputFile, netscapeFormat);
        console.log(`[+] SUCCESS! Cookies perfectly extracted and saved to: ${outputFile}`);

    } catch (error) {
        console.error('[-] Error or timeout:', error.message);
        console.log('[-] Did you take longer than 5 minutes to log in?');
    } finally {
        console.log('[*] Closing browser...');
        await browser.close();
    }
})();
